### ISSUE TITLE
Cross Group Testing 1

### ISSUE THREAD

**Issue by harlach** [folkebl/Operation-Squirrel#28]
That The Menu Bar Text Blends in with the Background pictures, make it so that you can tell on what you are clicking on in the menu bar

**Comment by XsmithjoX** [comment]
Seller fees should be charged starting with the 6th item sold. They're currently charged for all items sold.

**Comment by harlach** [comment]
The Report doen't work need to get it actually functional

**Comment by XsmithjoX** [comment]
Alert Item Description is empty when seller notes field is empty.

**Comment by harlach** [comment]
should add a upload picture option to the items so that people can see what it is they are buying not just a description

**Comment by folkebl** [comment]
Fixed the bugs. The add upload pictures doesn't fit the scope of the project so it will not be implemented.
