### ISSUE TITLE
Cross testing #2

### ISSUE THREAD

**Issue by giji48** [folkebl/Operation-Squirrel#29]
Great project!

**Comment by giji48** [comment]
Under the Sell Items tab- change 'condition' to 'Item Condition' for clarification

**Comment by giji48** [comment]
Header Bar- give background to text
make same for all pages
(HTML special characters)

**Comment by giji48** [comment]
Auto-focus- in Admin under the registration page - focus to the first line

**Comment by giji48** [comment]
Make the box a lighter color- perhaps a div box

**Comment by giji48** [comment]
Add a username and registration for admin page

**Comment by giji48** [comment]
Under the add page for adding a person add some error handling for phone registration

**Comment by folkebl** [comment]
changed "condition" to "item condition", added username and password for admin page, fixed the auto focus, and the CSS is being worked on in the other issue.
